apiVersion: v1
kind: Service
metadata:
  name: listings
  labels:
    app: listings-service
spec:
  type: ClusterIP
  selector:
    app: listings
  ports:
    - protocol: TCP
      port: {{ .Values.backend.listings.service.port }}
      targetPort: {{ .Values.backend.listings.service.port }}
