apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    app: chat-service
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: {{ .Values.backend.chat.service.port }}
      targetPort: {{ .Values.backend.chat.service.port }}
