apiVersion: v1
kind: Secret
metadata:
  name: transcendence-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}