apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front-service
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}