# Default values for transcendence.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: transcendence

configMap:
  HOST: "0.0.0.0"
  GATEWAY_PORT: "443"
  AUTH_SERVICE_PORT: "3004"
  CHAT_SERVICE_PORT: "3001"
  USER_SERVICE_PORT: "3002"
  FRONT_SERVICE_PORT: "3003"
  LISTINGS_SERVICE_PORT: "3005"
  AI_SERVICE_PORT: "3006"
  APP_URL: "https://localhost/"
  FRONTEND_URL: "http://localhost:3003/"
  DB_USER: "postgres"
  DB_NAME: "postgres"
  JWT_EXPIRES_IN: "7d"
  DATABASE_URL: "postgresql://postgres:12345678@database:5432/postgres?schema=public"
  ELASTIC_VERSION: "7.17.21"
  ELASTIC_SECURITY: "false"
  POSTGRES_PORT: "5432"
  INTRA42_CALLBACK_URL: "https://localhost/api/auth/42/callback"
  GOOGLE_CALLBACK_URL: "https://localhost/api/auth/google/callback"

nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: localhost:5555/nginx
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 443
  tlsSecretName: nginx-certs

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: localhost:5555/front
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3003

backend:
  database:
    enabled: true
    replicaCount: 1
    image:
      repository: localhost:5555/postgres
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 5432
  auth:
    enabled: true
    replicaCount: 1
    image:
      repository: localhost:5555/auth
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3004
  chat:
    enabled: true
    replicaCount: 1
    image:
      repository: localhost:5555/chat
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3001
  user:
    enabled: true
    replicaCount: 1
    image:
      repository: localhost:5555/user
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3002
  listings:
    enabled: true
    replicaCount: 1
    image:
      repository: localhost:5555/listings
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3005
  ai:
    enabled: true
    replicaCount: 1
    image:
      repository: localhost:5555/ai
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3006
