apiVersion: v1
kind: Service
metadata:
  name: ai
  labels:
    app: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai
  ports:
    - protocol: TCP
      port: {{ .Values.backend.ai.service.port }}
      targetPort: {{ .Values.backend.ai.service.port }}
