apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: {{ .Values.backend.auth.service.port }}
      targetPort: {{ .Values.backend.auth.service.port }}
