apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database-service
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - protocol: TCP
      port: {{ .Values.backend.database.service.port }}
      targetPort: {{ .Values.backend.database.service.port }}
